### ISSUE TITLE
I just upgraded the addon via the addon's details page, and now if I try to start it, it won't do it, and the button will keep saying "start". I'm running hassio 195, HassOS 3.7, on a raspberry pi 3b+. No logs are being created, even the log_level set to debug. addon version 2.2.2. Any hint?

### ISSUE THREAD

**Issue by ggallegosm** [hassio-addons/addon-aircast#24] opened 2020-01-13 02:08 UTC
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment] 2020-01-13 09:44
First of all, the subject is a small think of what the problem is.
Then we have the body which asks all kinds of questions and gives room for extensive descriptions.

You just put a story in the description, which makes it really annoying and hard to read.

Check the Hass.io Supervisor logs for hints.

Closing this issue, Feel free to open a new decent one when in need of additional assistance. Thanks.

**Closed by frenck** 2020-01-13 09:44 UTC
