### ISSUE TITLE
Cannot cast photos or videos from iOS photos app

### ISSUE THREAD

**Issue by svillar** [hassio-addons/addon-aircast#25] opened 2020-02-07 18:45 UTC
# Problem/Motivation

I'm trying to cast a photo or a video from iOS photos app.

## Expected behavior

The ChromeCast device is listed as a AirPlay cabable device

## Actual behavior

Nothing is shown

## Steps to reproduce

1- Open iOS photos app
2- Click on a photo/video
3- Click on share icon
4- Select AirPlay from the menu
5- An empty list of devices is shown

**Comment by sinclairpaul** [comment] 2020-02-07 18:51
Duplicate of #10 

Unfortunately only audio is supported.

**Closed by sinclairpaul** 2020-02-07 18:51 UTC
